name: autoencoder-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - pytorch-lightning
  - scikit-learn
  - pandas
  - numpy
  - pip
  - matplotlib
  - seaborn
  - pip:
    - wandb

